app = 'listen-kit'
primary_region = 'waw'

[build]

[env]
PORT = '6969'

# Main HTTP Service with SSE support
[http_service]
internal_port = 6969
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

# Additional HTTP service for engine
[[services.ports]]
port = 6966
handlers = ["http"]
force_https = true

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
