[package]
name = "listen"
version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
description.workspace = true

[dependencies]
clap.workspace = true
dotenv.workspace = true
flexi_logger.workspace = true
jito-protos.workspace = true
tokio.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
solana-client.workspace = true
solana-sdk.workspace = true

listen-searcher-client.workspace = true
